export const data = {
  Christmas: require('../assets/icons/christmas.png'),
  Dark: require('../assets/icons/dark.png'),
  Explicit: require('../assets/icons/explicit.png'),
  Miscellaneous: require('../assets/icons/misc.png'),
  Nsfw: require('../assets/icons/nsfw.png'),
  Political: require('../assets/icons/political.png'),
  Programming: require('../assets/icons/programming.png'),
  Pun: require('../assets/icons/pun.png'),
  Racist: require('../assets/icons/racist.png'),
  Religious: require('../assets/icons/religious.png'),
  Sexist: require('../assets/icons/sexist.png'),
  Spooky: require('../assets/icons/spooky.png'),
  Moon: require('../assets/icons/moon.png'),
  Sun: require('../assets/icons/sun.png'),
  Check: require('../assets/icons/check.png'),
  Forbidden: require('../assets/icons/forbidden.png'),
  ArrowUp: require('../assets/icons/arrowUp.png'),
  ArrowDown: require('../assets/icons/arrowDown.png'),
};
